### ISSUE TITLE
'Error either in ArrayFire or in a project upstream' on arch Linux using arrayfire-rust 3.5.0

### ISSUE THREAD

**Issue by Haniyya** [arrayfire/arrayfire-rust#165]
There seems to be an Issue with the bindings on arch linux when initializing an array (or i guess basically anything).
Example code:
```rust
// src/main.rs
extern crate arrayfire;

use arrayfire::{Array, Dim4};

fn main() {
    let vs: [i32; 9] = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    let arr = Array::new(&vs, Dim4::new(&[3, 3, 1, 1]));
}
```
And the Cargo.toml
```toml
[dependencies]
arrayfire = "3.5"
```
The installed version is
```bash
$ pacman -Ss arrayfire
community/arrayfire 3.5.1-2 [Installiert]
    High performance software library for parallel computing with an easy-to-use API
```

And the resulting error:
```bash
 RUST_BACKTRACE=1 cargo run                                                                                            101 ↵  10103  13:51:27 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/arrayfire_demo`
thread 'main' panicked at 'Error message: Error either in ArrayFire or in a project upstream', /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:30:13
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: arrayfire::error::handle_error_general
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:30
   8: arrayfire::error::Callback::call
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:22
   9: arrayfire::error::HANDLE_ERROR
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:82
  10: arrayfire::array::Array::new
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/array.rs:155
  11: arrayfire_demo::main
             at src/main.rs:7
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  14: main
  15: __libc_start_main
  16: _start
```

I tried downgrading both arrayfire and the bindings to 3.4.2 i think the results were the same.
I hope this is not a duplicate, i couldn't find any.
And thanks for the help!

**Comment by 9prady9** [comment]
@Haniyya Are the rust cargo examples also reporting similar errors ?

**Comment by pavanky** [comment]
@Haniyya Can you run the program after running `export AF_PRINT_ERRORS=1`

**Comment by Haniyya** [comment]
@9prady9 Checking out 'v.3.5.0' or master the error is the same (tried helloworld and acoustic_wave).

@pavanky Running my example from above with `AF_PRINT_ERRORS=1` gives the following:
```
OpenCL Error (-1001): Unknown OpenCL Error (-1001) when calling clGetPlatformIDs
In function af_err af_create_array(void**, const void*, unsigned int, const dim_t*, af_dtype)
In file src/api/c/array.cpp:71



thread 'main' panicked at 'Error message: Error either in ArrayFire or in a project upstream', /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:30:13
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: arrayfire::error::handle_error_general
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:30
   8: arrayfire::error::Callback::call
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:22
   9: arrayfire::error::HANDLE_ERROR
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/error.rs:82
  10: arrayfire::array::Array::new
             at /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayfire-3.5.0/src/array.rs:155
  11: arrayfire_demo::main
             at src/main.rs:7
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```
So i installed [intels opencl](https://aur.archlinux.org/packages/intel-opencl/)
which works, though it is not as great as using my built in gpu. But that would
require nvidias proprietary drivers which is a can of worms that I'm not ready
to open right now.

Thanks for help! :)

**Comment by Haniyya** [comment]
Would be nice to have some diagnostics that could tell you whether you are missing dependencies (or, if arrayfire already has something similar, to link to it in the README).

**Comment by pavanky** [comment]
@Haniyya The error seems to indicate you already had an OpenCL driver installed. Probably mesa-opencl (which is known to be buggy) ?

**Comment by Haniyya** [comment]
@pavanky Sorry for the long wait. By now i have three packages pertaining to OpenCL installed:
`opencl-mesa opencl-nvidia intel-opencl-runtime`. I guess i had mesa and nvidia installed alongside each other.
Just out of curiosity i tried to run examples from [this ocl lib](https://github.com/cogciprocate/ocl) which told me there were no ocl devices (CL_DEVICE_NOT_FOUND). 
Btw im trying to follow [arch linux's](https://wiki.archlinux.org/index.php/GPGPU) instructions on the topic but i seem to be to  stupid for it. Is there any good setup guide oder health-check that I could use to diagnose my system?

**Comment by pavanky** [comment]
@Haniyya Can you try after uninstalling `opencl-mesa` ?

**Comment by Haniyya** [comment]
@pavanky Without either mesa or intels opencl both arrayfire and rust-ocl are unable to find a opencl platform (unknown Error when calling clGetPlatformIDs). I reinstalled intel and am able to use it for both projects now.
For hardware reference:
`lspci`:
```
00:00.0 Host bridge: Intel Corporation Broadwell-U Host Bridge -OPI (rev 09)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
00:14.0 USB controller: Intel Corporation Wildcat Point-LP USB xHCI Controller (rev 03)
00:16.0 Communication controller: Intel Corporation Wildcat Point-LP MEI Controller #1 (rev 03)
00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)
00:1c.0 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 (rev e3)
00:1c.2 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #3 (rev e3)
00:1c.3 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 (rev e3)
00:1c.4 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #5 (rev e3)
00:1d.0 USB controller: Intel Corporation Wildcat Point-LP USB EHCI Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation Wildcat Point-LP LPC Controller (rev 03)
00:1f.2 SATA controller: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] (rev 03)
00:1f.3 SMBus: Intel Corporation Wildcat Point-LP SMBus Controller (rev 03)
00:1f.6 Signal processing controller: Intel Corporation Wildcat Point-LP Thermal Management Controller (rev 03)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
03:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 20)
04:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 950M] (rev ff)
```
And `lscpu` 
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Stepping:            4
CPU MHz:             2259.922
CPU max MHz:         3000.0000
CPU min MHz:         500.0000
BogoMIPS:            4791.63
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            4096K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap xsaveopt dtherm ida arat pln pts
```
So technically i have a compatible gpu, but maybe mesa-opencl is broken for it.

**Comment by 9prady9** [comment]
Intel reinstall probably installed the `ocl-icd` loader and hence you were able to use it after the reinstall. Closing the issue as the issue seems to be with `mesa-opencl` package.
