### ISSUE TITLE
Error with documented hellow world on Ubuntu 14.04 CUDA

### ISSUE THREAD

**Issue by tyrel86** [arrayfire/arrayfire-rust#76]
Hi, I have tried to compile your example hello world and I get
```bash
tyger42@minch-yoda:~/code/playground/array_fire/rust/my_first_af$ RUST_BACKTRACE=1 cargo run
     Running `target/debug/my_first_af`
Create a 5-by-3 matrix of random floats on the GPU
modprobe: ERROR: could not insert 'nvidia_352': No such device
thread '<main>' panicked at 'Error message: Eror either in ArrayFire or in a project upstream', /home/tyger42/.cargo/registry/src/github.com-88ac128001ac3a9a/arrayfire-3.3.1/src/error.rs:47
stack backtrace:
   1:     0x7f197d657650 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7f197d65983b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7f197d6594c3 - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7f197d65199f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7f197d652378 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7f197d64fc34 - arrayfire::error::handle_error_general::h850e86f50ea94bfe
                        at /home/tyger42/code/playground/array_fire/my_first_af/<std macros>:8
   7:     0x7f197d64fc4b - fn(defines..AfError) $u7b$error..handle_error_general$u7d$::fn_pointer_shim.13448::hcbcf2b22c9dc31c2
   8:     0x7f197d64efb0 - arrayfire::error::HANDLE_ERROR::hbd01e4994c2877f0
                        at /home/tyger42/.cargo/registry/src/github.com-88ac128001ac3a9a/arrayfire-3.3.1/src/error.rs:60
   9:     0x7f197d64ecdc - arrayfire::data::randu::h122f02e85e026c88
                        at /home/tyger42/.cargo/registry/src/github.com-88ac128001ac3a9a/arrayfire-3.3.1/src/data/mod.rs:282
  10:     0x7f197d64eb6a - my_first_af::main::hc5618c3a38539c0e
                        at src/main.rs:9
  11:     0x7f197d659104 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  12:     0x7f197d656abb - __rust_try
  13:     0x7f197d658b4b - std::rt::lang_start::h5b0863080165c75e
  14:     0x7f197d64ee19 - main
  15:     0x7f197c5f7a3f - __libc_start_main
  16:     0x7f197d64e8e8 - _start
  17:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/my_first_af` (exit code: 101)
```

here is my main.rs
```rust
extern crate arrayfire as af;
use af::*;

fn main() {
        let num_rows: u64 = 5;
        let num_cols: u64 = 3;
        let dims = Dim4::new(&[num_rows, num_cols, 1, 1]);
        println!("Create a 5-by-3 matrix of random floats on the GPU");
        let a = randu::<f32>(dims);
        print(&a);
}
```
And here is my graphics details
```bash
tyger42@minch-yoda:~/code/playground/array_fire/rust/my_first_af$ lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation GT216M [GeForce GT 330M] (rev a2)
```
Am I missing something or is this possibly a library issue? Thank you!

**Comment by 9prady9** [comment]
@tyrel86 

The error `modprobe: ERROR: could not insert 'nvidia_352': No such device`  doesn't seem to be from ArrayFire source code. Can you run the command `nvidia-smi` and see if any devices are being listed on your machine ?

Also, the card you have mentioned, `GT 330M`, is a `1.2` cuda compute version card which is not officially supported by ArrayFire binaries that you download from our website. If you want to use it on this card, you have to build ArrayFire from source after changing the build parameters to build for compute 1.2. You can find the build instructions from [here](https://github.com/arrayfire/arrayfire/wiki).

**Comment by pavanky** [comment]
@9prady9 arrayfire does not support 1.2 cards even if he recompiles it.

**Comment by pavanky** [comment]
This is because NVIDIA deprecated compute 1.2 and 1.3 cards from CUDA 6.5.

**Comment by 9prady9** [comment]
@tyrel86 As mentioned by @pavanky , 1.2 cards are not supported at all. I shall edit my earlier comment reflecting the same.

Closing the issue now.
